package app.enums;

public enum Nacionalidad {
    AFGANISTAN("Afganistán"),
    ALBANIA("Albania"),
    ALEMANIA("Alemania"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANTIGUA_Y_BARBUDA("Antigua y Barbuda"),
    ARABIA_SAUDITA("Arabia Saudita"),
    ARGELIA("Argelia"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIYÁN("Azerbaiyán"),
    BAHAMAS("Bahamas"),
    BANGLADES("Banglades"),
    BARBADOS("Barbados"),
    BARÉIN("Baréin"),
    BÉLGICA("Bélgica"),
    BELICE("Belice"),
    BENÍN("Benín"),
    BIELORRUSIA("Bielorrusia"),
    BIRMANIA("Birmania"),
    BOLIVIA("Bolivia"),
    BOSNIA_Y_HERZEGOVINA("Bosnia y Herzegovina"),
    BOTSUANA("Botsuana"),
    BRASIL("Brasil"),
    BRUNÉI("Brunéi"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    BUTÁN("Bután"),
    CABO_VERDE("Cabo Verde"),
    CAMBOYA("Camboya"),
    CAMERÚN("Camerún"),
    CANADÁ("Canadá"),
    CHAD("Chad"),
    CHILE("Chile"),
    CHINA("China"),
    CHIPRE("Chipre"),
    CIUDAD_DEL_VATICANO("Ciudad del Vaticano"),
    COLOMBIA("Colombia"),
    COMORAS("Comoras"),
    COREA_DEL_NORTE("Corea del Norte"),
    COREA_DEL_SUR("Corea del Sur"),
    COSTA_DE_MARFIL("Costa de Marfil"),
    COSTA_RICA("Costa Rica"),
    CROACIA("Croacia"),
    CUBA("Cuba"),
    DINAMARCA("Dinamarca"),
    DOMINICA("Dominica"),
    ECUADOR("Ecuador"),
    EGIPTO("Egipto"),
    EL_SALVADOR("El Salvador"),
    EMIRATOS_ÁRABES_UNIDOS("Emiratos Árabes Unidos"),
    ERITREA("Eritrea"),
    ESLOVAQUIA("Eslovaquia"),
    ESLOVENIA("Eslovenia"),
    ESPAÑA("España"),
    ESTADOS_UNIDOS("Estados Unidos"),
    ESTONIA("Estonia"),
    ETIOPÍA("Etiopía"),
    FILIPINAS("Filipinas"),
    FINLANDIA("Finlandia"),
    FIYI("Fiyi"),
    FRANCIA("Francia"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GRANADA("Granada"),
    GRECIA("Grecia"),
    GUATEMALA("Guatemala"),
    GUYANA("Guyana"),
    GUINEA("Guinea"),
    GUINEA_ECUATORIAL("Guinea Ecuatorial"),
    GUINEA_BISÁU("Guinea-Bisáu"),
    HAITÍ("Haití"),
    HONDURAS("Honduras"),
    HUNGRÍA("Hungría"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAK("Irak"),
    IRLANDA("Irlanda"),
    ISLANDIA("Islandia"),
    ISLAS_MARSHALL("Islas Marshall"),
    ISLAS_SALOMÓN("Islas Salomón"),
    ISRAEL("Israel"),
    ITALIA("Italia"),
    JAMAICA("Jamaica"),
    JAPÓN("Japón"),
    JORDANIA("Jordania"),
    KAZAJISTÁN("Kazajistán"),
    KENIA("Kenia"),
    KIRGUISTÁN("Kirguistán"),
    KIRIBATI("Kiribati"),
    LAOS("Laos"),
    LESOTO("Lesoto"),
    LETONIA("Letonia"),
    LÍBANO("Líbano"),
    LIBERIA("Liberia"),
    LIBIA("Libia"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIA("Lituania"),
    LUXEMBURGO("Luxemburgo"),
    MACEDONIA_DEL_NORTE("Macedonia del Norte"),
    MADAGASCAR("Madagascar"),
    MALASIA("Malasia"),
    MALAUI("Malaui"),
    MALDIVAS("Maldivas"),
    MALÍ("Malí"),
    MALTA("Malta"),
    MARRUECOS("Marruecos"),
    MAURICIO("Mauricio"),
    MAURITANIA("Mauritania"),
    MICRONESIA("Micronesia"),
    MOLDAVIA("Moldavia"),
    MÓNACO("Mónaco"),
    MONGOLIA("Mongolia"),
    MONTENEGRO("Montenegro"),
    MOZAMBIQUE("Mozambique"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NICARAGUA("Nicaragua"),
    NÍGER("Níger"),
    NIGERIA("Nigeria"),
    NORUEGA("Noruega"),
    NUEVA_ZELANDA("Nueva Zelanda"),
    OMÁN("Omán"),
    PAÍSES_BAJOS("Países Bajos"),
    PAKISTÁN("Pakistán"),
    PALAOS("Palaos"),
    PANAMÁ("Panamá"),
    PAPÚA_NUEVA_GUINEA("Papúa Nueva Guinea"),
    PARAGUAY("Paraguay"),
    PERÚ("Perú"),
    POLONIA("Polonia"),
    PORTUGAL("Portugal"),
    REINO_UNIDO("Reino Unido"),
    REPÚBLICA_CENTROAFRICANA("República Centroafricana"),
    REPÚBLICA_CHECA("República Checa"),
    REPÚBLICA_DEL_CONGO("República del Congo"),
    REPÚBLICA_DEMOCRÁTICA_DEL_CONGO("República Democrática del Congo"),
    REPÚBLICA_DOMINICANA("República Dominicana"),
    RUMANÍA("Rumanía"),
    RUSIA("Rusia"),
    SAMOA("Samoa"),
    SAN_CRISTÓBAL_Y_NIEVES("San Cristóbal y Nieves"),
    SAN_MARINO("San Marino"),
    SAN_VICENTE_Y_LAS_GRANADINAS("San Viciente y las Granadinas"),
    SANTA_LUCÍA("Santa Lucía"),
    SANTO_TOMÉ_Y_PRÍNCIPE("Santo Tomé y Príncipe"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONA("Sierra Leona"),
    SINGAPUR("Singapur"),
    SIRIA("Siria"),
    SOMALIA("Somalia"),
    SRI_LANKA("Sri Lanka"),
    SUAZILANDIA("Suazilandia"),
    SUDÁFRICA("Sudáfrica"),
    SUDÁN("Sudán"),
    SUDÁN_DEL_SUR("Sudán del Sur"),
    SUECIA("Suecia"),
    SUIZA("Suiza"),
    SURINAM("Surinam"),
    TAILANDIA("Tailandia"),
    TANZANIA("Tanzania"),
    TAYIKISTÁN("Tayikistán"),
    TIMOR_ORIENTAL("Timor Oriental"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_Y_TOBAGO("Trinidad y Tobago"),
    TURQUÍA("Turquía"),
    TUVALU("Tuvalu"),
    UCRANIA("Ucrania"),
    UGANDA("Uganda"),
    URUGUAY("Uruguay"),
    UZBEKISTÁN("Uzbekistán"),
    VANUATU("Vanuatu"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    YEMEN("Yemen"),
    YIBUTI("Yibuti"),
    ZAMBIA("Zambia"),
    ZIMBABUE("Zimbabue");

    private String displayName;

    private Nacionalidad(String displayName) {
        this.displayName = displayName;
    }
    
    public String getDisplayName(){
        return this.displayName;
    }

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return this.displayName;
    }

    
}
